version: '3'

services:
  reverse-proxy:
    image: traefik:v2.4  # Usa la versión de Traefik que prefieras
    command:
      - "--api.insecure=true"  # Habilita el dashboard (inseguro, úsalo solo en ambientes de desarrollo)
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--log.level=DEBUG"  # Cambia el nivel de logs a DEBUG
      - "--accessLog=true"  # Habilita los logs de acceso (opcional)
    ports:
      - "81:80"
      - "8081:8080"  # Para el dashboard de Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ms_pagos:
    image: ghcr.io/felix-orduz/ms_pagos_image:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms_pagos.rule=PathPrefix(`/api/pagos`)"
      - "traefik.http.routers.ms_pagos.entrypoints=web"
      - "traefik.http.services.ms_pagos.loadbalancer.server.port=5000"  # Indicar a Traefik que use el puerto 5000

  ms_users:
    image: ghcr.io/felix-orduz/ms_users_image:latest
    ports:
      - "5000:5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ms_users.rule=PathPrefix(`/api/users`)"
      - "traefik.http.routers.ms_users.entrypoints=web"
      - "traefik.http.services.ms_users.loadbalancer.server.port=5000"
      - "traefik.http.routers.ms_users.middlewares=strip-prefix"
      - "traefik.http.middlewares.strip-prefix.stripprefix.prefixes=/api/users"